apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood
  template:
    metadata:
      labels:
        app: fastfood
    spec:
      automountServiceAccountToken: false
      containers:
        - name: fastfood-app
          image: fastfood-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: fastfood-config
            - secretRef:
                name: fastfood-secrets